name: Auto-Clean

on:
  #自动清理：每周一早上4点
  schedule:
    - cron: 0 20 * * 0
  #手动清理
  workflow_dispatch:

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: false
          releases_keep_latest: 0
          delete_tags: false
          delete_workflows: true
          workflows_keep_day: 0
